QuizPlanet/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('user/',include('account.urls')),
    path('quiz/',include('quiz.urls')),
    
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path 
from . import views
urlpatterns = [
    path('',views.home,name='home'),
    path('leaderboard',views.leaderboard_view,name='leaderboard'),
    path('dashboard',views.dashboard_view,name='dashboard'),
    path('message/<int:id>:',views.message_view,name='message'),
    path('about',views.about_view,name='about'),
    path('blogs',views.blogs_view,name='blogs'),
    path('blogs/<str:blog_id>',views.blog_view,name='blog'),
    path('contact',views.contact_view,name='contact'),
    path('downloads',views.downloads_view,name='downloads'),
    path('termsandcondition',views.terms_and_conditions,name='termandcond'),
    path('search/users',views.search_user,name='search_users'),

]

quiz/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('all_quiz',views.all_quiz_view,name='all_quiz'),
    path('search/<str:category>',views.search_view,name='search'),
    path('<int:quiz_id>',views.quiz_view,name='quiz')
]

quiz/models.py
from django.db import models
import pandas as pd
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 15)
    class Meta:
        verbose_name_plural= 'Categories'
    def __str__(self):
        return self.name

class Quiz(models.Model):
    title=models.CharField(max_length=255)
    description= models.TextField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    quiz_file = models.FileField(upload_to='quiz/')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural= "Quizzes"
    
    def  __str__(self):
        return self.title
    
    # call the function on quize save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.quiz_file:
            if self.quiz_file.name.endswith('.xlsx'):
                self.import_quiz_from_excel()
            elif self.quiz_file.name.endswith('.csv'):
                self.import_quiz_from_csv()

    #fumction to extract exel file
    def import_quiz_from_excel(self):
        # Read the CSV file using pandas
        df = pd.read_excel(self.quiz_file.path)
        # Clean up column names by stripping leading and trailing spaces
        df.columns = df.columns.str.strip()
        print(df.columns)
        # Iterate over each row
        for index, row in df.iterrows():
            # Extract question text, choices, and correct answer from the row
            question_text = row['Question']
            choice1 = row['A']
            choice2 = row['B']
            choice3 = row['C']
            choice4 = row['D']
            correct_answer = row['Answer']

            # Create the question object 
            question = Question.objects.get_or_create(quiz=self, text=question_text)
            
            # Create choices objects[0]
            choice_1 = Choice.objects.get_or_create(question=question[0], text=choice1, is_correct=(correct_answer == 'A'))
            choice_2 = Choice.objects.get_or_create(question=question[0], text=choice2, is_correct=(correct_answer == 'B'))
            choice_3 = Choice.objects.get_or_create(question=question[0], text=choice3, is_correct=(correct_answer == 'C'))
            choice_4 = Choice.objects.get_or_create(question=question[0], text=choice4, is_correct=(correct_answer == 'D'))
    

class Question(models.Model):
    quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
    text=models.TextField()

    def  __str__(self):
        return self.text[:50]

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    text= models.CharField(max_length=255)
    is_correct  = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.question.text[:50]},{self.text[:20]}"
    
class QuizSubmission(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
    score = models.IntegerField()
    submitted_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}, {self.quiz.title}"

class UserRank(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    rank=models.IntegerField(null=True,blank =True)
    total_score = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return f"{self.rank}, {self.user.username}"

@receiver(post_save, sender=QuizSubmission)
def updated_leaderboard(sender, instance, created, **kwargs):
    if created:
        update_leaderboard()


def update_leaderboard():
    # Count the sum of all users' scores
    user_scores = QuizSubmission.objects.values('user').annotate(total_score=Sum('score')).order_by('-total_score')

    # Update rank based on the sorted list
    rank = 1
    for entry in user_scores:
        user_id = entry['user']
        total_score = entry['total_score']

        # Retrieve User instance
        user = User.objects.get(id=user_id)
        
        # Check if UserRank already exists for this user
        user_rank, created = UserRank.objects.get_or_create(user=user)
        
        # Update UserRank fields
        user_rank.rank = rank
        user_rank.total_score = total_score
        user_rank.save()

        rank += 1

quiz/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.models import User,auth
from account.models import Profile
from django.contrib.auth.decorators import login_required
from .models import Quiz,Category
from django.db.models import Q
from quiz.models import QuizSubmission
from django.shortcuts import get_object_or_404

# Create your views here.
@login_required(login_url='login')
def all_quiz_view(request):
    if(request.user.is_authenticated):
        user_object = User.objects.get(username=request.user)
        user_profile2 =Profile.objects.get(user=user_object)

    quizzes = Quiz.objects.order_by('-created_at')
    categories=Category.objects.all()

    context={"user_profile2":user_profile2,"quizzes":quizzes,"categories":categories,'quiz':'active'}
    return render(request,"all-quiz.html", context)

@login_required(login_url='login')
def search_view(request,category):
    user_object = User.objects.get(username=request.user)
    user_profile2 =Profile.objects.get(user=user_object)

    #search by category
    if request.GET.get('q') != None :
        q=request.GET.get('q')
        query=Q(title__icontains=q) | Q(description__icontains=q)
        quizzes=Quiz.objects.filter(query).order_by('-created_at')
    #serach by search bar
    elif category != " ":
        quizzes=Quiz.objects.filter(category__name=category).order_by('-created_at')
    else:
        quizzes = Quiz.objects.order_by('-created_at')

    categories = Category.objects.all()

    context={"user_profile2":user_profile2,"quizzes":quizzes,"categories":categories}
    return render(request,"all-quiz.html", context)


@login_required(login_url='login')
def quiz_view(request, quiz_id):
    user_object = User.objects.get(username=request.user)
    user_profile2 = get_object_or_404(Profile, user=user_object)

    quiz = Quiz.objects.filter(id=quiz_id).first()

    total_questions = quiz.question_set.all().count()

    if request.method == "POST":
        
        # Get the score
        score = int(request.POST.get('score', 0))

        # Check if the user has already submiited the quiz
        if QuizSubmission.objects.filter(user=request.user, quiz=quiz).exists():
            messages.success(request, f"This time you got {score} out of {total_questions}")
            return redirect('quiz', quiz_id)
        
        # save the new quiz submission
        submission = QuizSubmission(user=request.user, quiz=quiz, score=score)
        submission.save()
        
        messages.success(request, f"Quiz Submitted Successfully. You got {score} out of {total_questions}")
        return redirect('quiz', quiz_id)

    context = {"user_profile2": user_profile2, "quiz": quiz}
    return render(request, 'quiz.html', context)

templates/blogs.html
{% extends "index.html" %}
{% load static %}
{% block title %}Blogs - QuizPlanet{% endblock title %}
{% block content %}
    <h1 class="display-4 text-center my-5">Blogs</h1>

    <main>
        <div class="container col-md-6 col-sm-12">
            {% for year_count in year_blog_count  %}
            <h3>{{year_count.year}}-{{year_count.count}} blogs</h3>
            <ul class="list mb-4 p-3">
                {% for blog in blogs  %}
                    {% if blog.created_at|date:"Y" == year_count.year|stringformat:"s" %}
                        <li class="d-flex justify-content-between mb-2">
                            <a href="{% url "blog" blog.id %}">{{blog.title}}</a>
                            <span title="26 Jul 23 08:05 UTC" class="text-secondary">{{blog.created_at}}</span>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
    </main>

{% endblock content %}

templates/confirm.html
{% extends "index.html" %}
{% load static %}
{% block title %}{{request.user.username}}'s Profile-Delete confirmation - Profile-QuizPlanet{% endblock title %}
{% block content %}
  <h1 class="display-4 text-center my-5">Confirmation Page</h1>

  <div class="container">
    <form action="" method="POST" class="">
      {% csrf_token %}
        <p class="fs-4"><b>@{{request.user.username}}</b>, Are you sure you want to delete your profile.</p>
        <a href="{% url "profile" request.user.username %}" class="btn btn-success" type="button">Back to Home</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
  </div>
{% endblock content %}

templates/contact.html
{% extends "index.html" %}
{% load static %}
{% block title %}Contact-QuizPlanet{% endblock title %}
{% block content %}


	<h1 class="display-4 text-center my-5">Contact Us</h1>

	<main>
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6">
					<div>
						{% for message in messages %}
							<h5 class="text-warning text-center">{{message}}</h5>
						{% endfor %}
					</div>
					<form action="" method="POST" class="contact-form">
						{% csrf_token %}
						<div class="form-group mb-4">
							<label for="username">Username</label>
							<input type="text" id="username" name="username" value="{{request.user.username}}" class="form-control"
								disabled>
						</div>

						<div class="form-group mb-4">
							<label for="subject">Subject</label>
							<input type="text" id="subject" name="subject" required class="form-control">
						</div>

						<div class="form-group mb-4">
							<label for="message">Message</label>
							<textarea id="message" name="message" rows="5" required class="form-control"></textarea>
						</div>

						<button type="submit" class="btn btn-primary btn-block">Send Message</button>
					</form>
				</div>
			</div>
		</div>
	</main>
{% endblock content %}
	

templates/dashboard.html
{% extends "index.html" %}
{% load static %}
{% block title %}Dashboard-QuizPlanet{% endblock title %}
{% block content %}
    <h1 class="display-4 text-center my-5">Dashboard</h1>

    <!-- Dashboard Code Goes Here -->
    <div class="container">
        <div class="row">
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_user}}</h1>
                        <p class="card-text">Active Users</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_users}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_users|default:"0"}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_quizzes}}</h1>
                        <p class="card-text">Quizzes</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_quizzes}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_quizzes|default:"0"}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_quiz_submit}}</h1>
                        <p class="card-text">Submissions</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_quiz_submit}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_quiz_submit|default:"0"}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_question}}</h1>
                        <p class="card-text">Questions</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_question}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_question|default:"0"}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-12 mb-3">
                <h2 class="mb-3 text-center">Inbox</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Username</th>
                            <th scope="col">Subject</th>
                            <th scope="col">Time</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in messages %}
                            <tr class="table-{% if not message.is_read %}active{% endif %}">
                                <th scope="row"><{{forloop.counter}}>
                                <td><a href="{% url "profile" message.user.username %}">@{{ message.user.username }}</a></td>
                                <td>{{ message.subject }}</td>
                                <td>{{ message.created_at }}</td>
                                <td><a href="{% url "message" message.id %}" class="btn btn-sm btn-primary">Open</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock content %}

templates/downloads.html
{% extends "index.html" %}
{% load static %}
{% block title %}Downloads-QuizPlanet{% endblock title %}
{% block content %}

    <h1 class="display-4 text-center my-5">Downloads</h1>


    <main>
        <div class="container col-md-8 col-sm-12">
            <div class="download-item mb-4">
                <h2 class="">Research Paper 1</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                    explicabo eos molestias enim itaque, quis nam.</p>
                <a href="" class="btn btn-primary">Download</a>
                <hr>
            </div>
            <div class="download-item mb-4">
                <h2>Reports</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                    explicabo eos molestias enim itaque, quis nam.</p>
                <a href="" class="btn btn-primary">Download</a>
                <hr>
            </div>
            <div class="download-item mb-4">
                <h2>Research Paper 1</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                    explicabo eos molestias enim itaque, quis nam.</p>
                <a href="" class="btn btn-primary">Download</a>
                <hr>
            </div>
        </div>
    </main>

{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

<body>
    {% include "components/navbar.html" %}

    {% block content %}{% endblock content %}

    {% include "components/footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>

    <script >
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
</body>

</html>

templates/leaderboard.html
{% extends 'index.html' %}

{% block title %}leaderboard - QuizPlanet{% endblock title %}

{% block content %}

    <div class="container text-center">
        <h1 class="display-4 text-center my-5">Leaderboard</h1>

        <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 mx-3">
            {% if leaderboard_users|length == 0 %}
                <div class="col-lg-4 position-relative mb-4">
                <h4 class="text-center text-danger">No User Available On Leaderboard</h4>
            {% else %}
                {% for rank in leaderboard_users  %}
                    <div class="col-lg-4 position-relative mb-4">
                        <img src="{{ rank.user.profile.profile_img.url }}" class="img-fluid" width="150" height="150" alt="user-profile">
                        <span class="position-absolute top-0 start-90 translate-middle badge rounded-pill bg-success">{{ forloop.counter }}</span>
                        <h2 class="fw-normal">@{{ rank.user.username }}</h2>
                        <p>{{ rank.user.profile.bio|truncatewords:5 }}</p>
                        <p><a class="btn btn-secondary" href="{% url "profile" rank.user.username %}">View Profile »</a></p>
                    </div>
                {% endfor %}
            {% endif %}  
        </div>
    </div>
{% endblock content %}

templates/login.html
{% extends "index.html" %}
{% block title %} Login Page-QuizPlanet{% endblock title %}
{% block content %}

    <h1 class="display-4 text-center my-5">Login</h1>

    <div class="container">
        <div class="row row-cols-sm-1 row-cols-lg-3 container">
            <div class="col-12">
            </div>
            <div class="col-12">
                <div>
                    {% for message in messages %}
                        <h5 class="text-danger">{{message}}</h5>
                    {% endfor %}
                </div>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label visually-hidden">Username</label>
                        <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label visually-hidden">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                        <label class="form-check-label" for="exampleCheck1">Remember me</label>
                    </div>
                    <button type="submit" class="btn btn-primary px-5">Login</button>
                </form>
                <p class="my-4">Not a member yet? <b><a href="{% url "register" %}">Register</a></b></p>
            </div>
            <div class="col-12">
            </div>
        </div>
    </div>
{% endblock content %}

templates/message.html
{% extends "index.html" %}
{% block title %}message form {{message.user.username}} - QuizPlanet{% endblock title %}
{% block content %}
    <h1 class="display-4 text-center my-5">Message From @{{message.user.username}}</h1>

    <main>
        <div class="container col-md-8 col-sm-12">
            <article>
                <sub>From</sub>
                <p class="" title="click to see profile"><a href="{% url "profile" message.user.username %}">@{{message.user.username}}</a></p>
                <sub>Received At</sub>
                <p>{{message.created_at}}</p>
                <sub>Subject</sub>
                <p>{{message.subject}}</p>
                <sub>Message</sub>
                <p>{{message.message}}</p>
            </article>
        </div>
    </main>


{% endblock content %}

templates/quiz.html
{% extends 'index.html' %}

{% block title %}{{quiz.title}} - QuizPlanet{% endblock title %}

{% block content %}

    <h1 class="display-4 text-center my-5">{{quiz.title}} - ({{quiz.question_set.all|length}})</h1>
    <p class="fs-4 text-center container">{{quiz.description}}</p>

    <div class="container">
        <div class="d-flex justify-content-between">
            <span class="fs-5">{{quiz.created_at}}</span>
            <span class="fs-5" id="timer">{{quiz.question_set.all|length}}:00</span>
        </div>

        {% for message in messages %}
        <div id="message-div">
            <h4 class="text-center text-success">{{message}}</h4>
        </div>
        {% endfor %}


        <div class="questions my-4">
            {% for question in quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold">
                    Question {{forloop.counter}}
                </div>
                <div class="card-body">
                    <p class="card-text">{{question.text}}</p>
                    {% for option in question.choice_set.all %}
                    <div class="form-check">
                        <label class="form-check-label" for="{{option.id}}">
                            <input class="form-check-input" value="{{option.text}}" type="radio" name="{{option.question.id}}" id="{{option.id}}">
                            {{option.text}}
                        </label>
                        {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <form action="" method="post" id="quiz-form">
            {% csrf_token %}
            <!-- hidden input field for score -->
            <input type="hidden" name="score" value="0" id="user-score">

            <!-- submit button -->
            <button type="submit" class="btn btn-primary" id="submit-button">Submit the quiz</button>
        </form>

    </div>

<script>
    // Elements
    var submitButton = document.getElementById("submit-button");
    var timerSpan = document.getElementById("timer");
    var quizForm = document.getElementById("quiz-form");
    var questions = document.querySelectorAll(".question");
    var userScoreInput = document.getElementById("user-score");

    quizDuration = (questions.length) * 60; // convert in seconds
    
    // Update Timer
    function updateTimer() {
        var minutes = Math.floor(quizDuration / 60);
        var seconds = quizDuration % 60;

        timerSpan.innerText = minutes + "m" + seconds + 's';

        // Check if the time ended
        if (quizDuration <= 0) {
            // Automatically Submit the quiz
            clearTimeout(quizTimerId);
            submitQuiz();
        } else if (document.getElementById("message-div")) {
            clearTimeout(quizTimerId);
            highlightCorrectAnswers();
        } else {
            // decrement the timer value by 1s
            quizDuration--;
        }
    }

    // Function to submit the quiz
    function submitQuiz() {
        // Calculate the score
        calculateScore();

        // Submit the quiz
        quizForm.submit();
    }

    // Check right answer and then calculate the score
    function calculateScore() {
        var score = 0;

        // Loop through each question
        questions.forEach(question => {
            var selectedInput = question.querySelector('input:checked');
            var correctAnswer = question.querySelector(".correct-answer").innerText;

            // Check if the answer is correct or not
            if (selectedInput && selectedInput.value === correctAnswer) {
                score += 1;
            }
        });

        // Update the hidden input field with score in form
        userScoreInput.value = score;
    }

    // highlight correct answer while showing result
    function highlightCorrectAnswers() {
        questions.forEach(question => {
            var correctAnswer = question.querySelector(".correct-answer");
            correctAnswer.previousElementSibling.querySelector("input").classList.add("bg-success");
            correctAnswer.previousElementSibling.classList.add("fw-bold");
        });

        // disable submit button
        submitButton.disabled = true;

        // disabel all options
        var options = document.querySelectorAll(".form-check-input");
        options.forEach(option => {
            option.disabled = true;
        });
    }

    // Attach Event Listener to Submit button
    submitButton.addEventListener("click", submitQuiz);
    // Timer Interval
    quizTimerId = setInterval(updateTimer, 1000);
</script>


{% endblock content %}

templates/welcome.html
{% extends "index.html" %}
{% load static %}
{% block content %}
    <div class="container text-center my-5">
        <h1 class="display-5 fw-bold my-2">Welcome to QuizPlanet</h1>
        <p class="fs-3">Not just make your ranking in college but also in knowledge</p>
        <div class="d-inline-flex gap-2 mb-5">
            <a href="{% url "all_quiz" %}" class="d-inline-flex align-items-center btn btn-primary btn-lg px-4">
                Take a quiz
            </a>
            {% if not request.user.is_authenticated %}
            <a href="{% url 'register' %}" class="btn btn-outline-secondary btn-lg px-4" type="button">
                Sign Up
            </a>
            {% endif %}
        </div>
    </div>

    <div class="container text-center">
        <h1 class="display-4 text-center my-5">Leaderboard</h1>
        <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-1 row-cols-xl-4 mx-3 text-center">
            {% if leaderboard_users|length == 0 %}
                <h4 class="text-danger">No User Available On Leaderboard</h4>
            {% else %}
            {% for rank in leaderboard_users %}
            <div class="col-lg-4 position-relative mb-4">
                <img src="{{ rank.user.profile.profile_img.url }}" class="img-fluid" width="150" height="150" alt="user-profile">
                <span class="position-absolute top-0 start-90 translate-middle badge rounded-pill bg-success">{{ forloop.counter }}</span>
                <h2 class="fw-normal">@{{ rank.user.username }}</h2>
                <p>{{ rank.user.profile.bio|truncatewords:5 }}</p>
                <p><a class="btn btn-secondary" href="{% url "profile" rank.user.username %}">View Profile »</a></p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}